version: "3"
services:

  web:
    build: ./web
    image: benrbray/yaraku-web
    environment:
      - PYTHONUNBUFFERED=1   # necessary to see python stdout in logs
    #command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    ports:
      - 5000:5000
    volumes:
      - data_volume:/opt/yaraku/data
    depends_on:
      - redis

  ml:
    build: ./ml
    image: benrbray/yaraku-ml
    environment:
      - PYTHONUNBUFFERED=1   # necessary to see python stdout in logs
    #command: gunicorn -w 4 -b 0.0.0.0:6000 app:app
    ports:
      - 5001:5000
    volumes:
      - data_volume:/opt/yaraku/data
    depends_on:
      - redis

  redis:
    image: redis
    volumes:
      - redis:/data
    ports: 
      - 6379:6379

volumes:
  data_volume:
  redis: