# Dockerfile
FROM python:3

WORKDIR /opt/yaraku-worker 

# install dependencies for python (done first for docker caching)
COPY ./worker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy application code
COPY ./worker .
COPY ./shared .