version: "3"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: benrbray/yaraku-web
    environment:
      - PYTHONUNBUFFERED=1   # necessary to see python stdout in logs
    command: gunicorn -w 4 -b 0.0.0.0:5000 "yaraku_web:create_app()"
    ports:
      - 5000:5000
    depends_on:
      - redis

  ml:
    build: 
      context: .
      dockerfile: Dockerfile.ml
    image: benrbray/yaraku-ml
    environment:
      - PYTHONUNBUFFERED=1   # necessary to see python stdout in logs
    command: gunicorn -w 1 -b 0.0.0.0:5000 "yaraku_ml:create_app()"
    ports:
      - 5001:5000
    depends_on:
      - redis

  worker:
    build: 
      context: .
      dockerfile: Dockerfile.worker
    image: benrbray/yaraku-worker
    environment:
      - PYTHONUNBUFFERED=1   # necessary to see python stdout in logs
    command: rq worker --url redis://redis:6379/0
    depends_on:
      - redis
      - ml

  redis:
    image: redis
    volumes:
      - redis:/data
    ports: 
      - 6379:6379
  
  tests:
    build: ./tests
    image: benrbray/yaraku-tests
    # keep container running for testing purposes
    command: tail -f /dev/null
    depends_on:
      - redis
      - web
      - ml
      - worker

volumes:
  redis: